version: 0.2

env:

  variables:

    build_version: "0.1"

phases:

  install:

    commands:

      - apt-get install git

  build:

    commands:

      - echo "Building firts Application"

artifacts:

  type: zip

  files:

    - ec2.json

  discard-paths: yes
