version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file cftrole.yaml --s3-bucket lambda-mohan-codepipeline --output-template-file outputcftrole.yaml
artifacts:
  type: zip
  files:
    - cftrole.yml
